language: c
compiler: clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y check
before_script:
  - cd ..
  - git clone https://github.com/tabascoeye/lwip-contrib.git
  - cd lwip-contrib/ports/unix/check
script:
  - make check
