language: c
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y check
  - sudo pip install cpp-coveralls
before_script:
  - cd ..
  - git clone https://github.com/tabascoeye/lwip-contrib.git
  - cd lwip-contrib/ports/unix/check
script:
  - make && make check
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp' -r ../../../../lwip -b .
